<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKsQ8Er6\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKsQ8Er6/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKsQ8Er6.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKsQ8Er6\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerKsQ8Er6\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'KsQ8Er6',
    'container.build_id' => '38c99e5c',
    'container.build_time' => 1630517448,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKsQ8Er6');
