<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMKwxyed\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMKwxyed/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMKwxyed.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMKwxyed\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerMKwxyed\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'MKwxyed',
    'container.build_id' => '8242e4ca',
    'container.build_time' => 1630945788,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMKwxyed');
