<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCyAdm4I\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCyAdm4I/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCyAdm4I.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCyAdm4I\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerCyAdm4I\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'CyAdm4I',
    'container.build_id' => 'bc70799b',
    'container.build_time' => 1630480123,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCyAdm4I');
